// < /auto-generated>
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This model file is automatically generated.
// Do NOT edit this file directly. Your changes will be lost
// next time you regenerate the models.
//
// You can extend this class by creating a new partial class of the same name in a
// different file.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

using System.ComponentModel.DataAnnotations;
using System.CodeDom.Compiler;
using IronERP.Core.Data;
using IronERP.Core.Schema;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using IronERP.Core.Data;

namespace IronERP.Web.Models;

[GeneratedCode("IronERP.Generators", "1.0.0+794e75c446a90e1b199df891d2b5b57590bde711")]
public partial class Demo : IModel
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }
    
    
        [Required]
        
        
        [FieldLabel("Name")]
        public string Name { get; set; }
        
        [Required]
        [SecretField]
        
        [FieldLabel("Secret")]
        public string Secret { get; set; }
        
        [Required]
        
        [RedactedField]
        [FieldLabel("Redacted")]
        public string Redacted { get; set; }
        
}