// < /auto-generated>
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// This model file is automatically generated.
// Do NOT edit this file directly. Your changes will be lost
// next time you regenerate the models.
//
// You can extend this class by creating a new partial class of the same name in a
// different file.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

using System.ComponentModel.DataAnnotations;
using System.CodeDom.Compiler;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using IronERP.Core.Data;

namespace ErpDemo.Models;

[GeneratedCode("IronERP.Generators", "1.0.0+0dbad4b7db40cd3a05918e97f36f9b6a8fe48331")]
public partial class Demo : IModel
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; }
    
    
        
        public string Name { get; set; }
        
}