using IronERP.Core.Schema;

namespace IronERP.CommandLine.Generator;

public class CsFileGenerator
{
    private const string Template = """
                                    // < /auto-generated>
                                    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                    // This model file is automatically generated.
                                    // Do NOT edit this file directly. Your changes will be lost
                                    // next time you regenerate the models.
                                    //
                                    // You can extend this class by creating a new partial class of the same name in a
                                    // different file.
                                    // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                                    
                                    using System.ComponentModel.DataAnnotations;
                                    using System.CodeDom.Compiler;
                                    using IronERP.Core.Data;
                                    using IronERP.Core.Schema;
                                    using MongoDB.Bson;
                                    using MongoDB.Bson.Serialization.Attributes;
                                    using IronERP.Core.Data;
                                    
                                    namespace {{ model.namespace }};
                                    
                                    [GeneratedCode("{{ generator_name }}", "{{ generator_version }}")]
                                    public partial class {{ model.name }} : IModel
                                    {
                                        [BsonId]
                                        [BsonRepresentation(BsonType.ObjectId)]
                                        public string Id { get; set; }
                                        
                                        {{ for field in model.fields }}
                                        {{ if field.required }}[Required]{{ end }}
                                        {{ if field.secret }}[SecretField]{{ end }}
                                        {{ if field.redacted }}[RedactedField]{{ end }}
                                        [FieldLabel("{{ field.label }}")]
                                        public {{ field.type }} {{ field.name }} { get; set; }
                                        {{ end }}
                                    }
                                    """;

    public static string? Generate(Model model, string generatorName, string generatorVersion)
    {
        var tpl = Scriban.Template.Parse(Template);
        if (tpl is not null)
        {
            var rendered = tpl.Render(new { generatorName, generatorVersion, model});
            return rendered;
        }

        return null;
    }
}