name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      SOLUTION: IronERP.sln
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Nuget
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore
        run: nuget restore ${SOLUTION}
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.x.x
      - name: Build
        run: dotnet build ${SOLUTION} --configuration ${BUILD_CONFIG} --no-restore
      - name: Tests
        run: dotnet test --configuration ${BUILD_CONFIG}