name: Publish

on:
  workflow_dispatch: 
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace }}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
      
      - name: Pack
        run: | # We only want to build Web and Core for NuGet
          dotnet pack IronERP.Core --configuration Release --output ${{ env.NuGetDirectory }} -p:VersionPrefix=${{ github.ref_name }}
          dotnet pack IronERP.Web --configuration Release --output ${{ env.NuGetDirectory }} -p:VersionPrefix=${{ github.ref_name }}
      
      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          if-no-files-found: error
          retention-days: 7
          path: ${{ env.NuGetDirectory }}/*.nupkg
  
  run_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
      
      - name: Run tests
        run: dotnet test --configuration Release
  
  push:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ create_nuget, run_test ]
    permissions: 
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: ${{ env.NuGetDirectory }}
      
      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          source-url: https://nuget.pkg.github.com/IronERP/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push NuGet
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file -k "${{ secrets.GITHUB_TOKEN }}" --skip-duplicate
          }